# Generated by Django 4.2 on 2023-04-28 00:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workorder_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='WorkOrderOrder',
        ),
        migrations.RenameModel(
            old_name='OrderItem',
            new_name='WorkOrderOrderItem',
        ),
    ]
