# Generated by Django 4.2 on 2023-04-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0002_department_location_product_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
